### PR TITLE
Translation in german 

### PR DESCRIPTION
**Pull request by ayushi-ras**
issue #68 
Work in progress will update soon

### CODE REVIEW

**Comment by ayushi-ras** [comment]
Hey @sumn2u can you help me to solve the conflict

**Comment by ayushi-ras** [comment]
Please merge it will work on it later

**Review by sumn2u — CHANGES_REQUESTED** [review]
Looks good. Is it possible to rename the folder to `de`?  We are using the ISO code in translation and for Germany it's `de`.

**Comment by ayushi-ras** [comment]
Ok

**Comment by ayushi-ras** [comment]
Updated the folder name but Deployment failed
What to do?

**Review by sumn2u — APPROVED** [review]
LGTM

**Pull request merged**
