### PR TITLE
add translated by section in credits.md

### PR DESCRIPTION
**Pull request by sumn2u**
Added translated by section in Spanish translation.

Screenshot 2024-09-07 at 11 59 22 AM

### CODE REVIEW

**Comment by sumn2u** [comment]
Hi @hamfree, can you review this PR?

**Comment by hamfree** [comment]
Hi, Sumn2u!

I'm at a loss for words. What do I have to revise? It's your book. I'm just one of the translators. Do what you think is best.

Anyway, thank you very much!

**Comment by sumn2u** [comment]
> Hi, Sumn2u!
> 
> I'm at a loss for words. What do I have to revise? It's your book. I'm just one of the translators. Do what you think is best.
> 
> Anyway, thank you very much!

Could you please verify if the translation and the link I provided in this section are accurate? Once again, I truly appreciate your work in translating the book!

Screenshot 2024-09-07 at 1 16 30 PM

**Comment by hamfree** [comment]
The link, the name and the image is ok, but the content of the alt attribute would be 
"Fotografía del traductor". I'm not a girl, you know ... :-D

**Comment by sumn2u** [comment]
> The link, the name and the image is ok, but the content of the **alt** attribute would be "Fotografía **_del traductor_**". I'm not a girl, you know ... :-D

My apologies. I've updated the text accordingly. It should be good now.

**Comment by hamfree** [comment]
All is ok now!
Thanks!

**Pull request merged**
