### PR TITLE
Write space and time complexity chapter

### PR DESCRIPTION
**Pull request by starvader13**
This MR aims to solve issue https://github.com/sumn2u/learn-javascript/issues/112

Considering space and time complexity is a significant aspect of programming that ensures code efficiency, scalability, and maintainability. Having a brief introduction to these concepts, followed by example, can greatly benefit JavaScript developers.

### CODE REVIEW

**Comment by starvader13** [comment]
@sumn2u Can you have a look if I am going on to the right path or not ?

**Comment by sumn2u** [comment]
> @sumn2u Can you have a look if I am going on to the right path or not ?

Looking great. If possible can you describe `O(log n)` and `O(n^2)` too?

**Comment by starvader13** [comment]
> Looking great. If possible can you describe `O(log n)` and `O(n^2)` too?

Roger that! I will add code snippets for that. 

Been busy with some work. I will ping you with the updated changes

**Comment by starvader13** [comment]
> Been busy with some work. I will ping you with the updated changes

Starting with the work from today. Thanks for being patient with me @sumn2u

**Comment by sumn2u** [comment]
> > Hey @starvader13, today is the last day of Hacktoberfest. Do you think you can create a pull request by the end of the day?
> 
> Should I divide it into two PRs, if possible?? You can accept this change for now and the rest I can change it in the next PR.
> 
> Or if this is not possible we can move forward with this without considering it for Hacktoberfest and I will push the changes ASAP.

If it's going to easier for you to split, i suggest to split. If not it's ok to have it in a single PR.

**Review by sumn2u — APPROVED** [review]

**Comment by sumn2u** [comment]
@starvader13  You can add your create another PR with remaining contents.

**Pull request merged**
