### PR TITLE
I have added content to interview questions basic and advanced section

### PR DESCRIPTION
**Pull request by kumar007ambi**
#74 I want to add some more contents in Interview Questions

### CODE REVIEW

**Comment by kumar007ambi** [comment]
@sumn2u Please review this PR

**Review by sumn2u — CHANGES_REQUESTED** [review]
I think the changes made look great. Would it be possible to exclude the `package-lock.json` and `yarn.lock` files from this pull request?

**Comment by kumar007ambi** [comment]
@sumn2u okay I will remove it from the PR

**Review by sumn2u — APPROVED** [review]
LGTM

**Pull request merged**
