### PR TITLE
Update basic-level_interview_questions.md

### PR DESCRIPTION
**Pull request by 05hiteshbansal**
added types of errors in JavaScript in basic level  interview questions

### CODE REVIEW

**Comment by 05hiteshbansal** [comment]
@sumn2u please merge my PR

**Comment by 05hiteshbansal** [comment]
@sumn2u  please review my PR

**Comment by 05hiteshbansal** [comment]
@sumn2u please Review my PR

**Review by sumn2u — APPROVED** [review]
Thanks for mentioning all those errors.

**Comment by 05hiteshbansal** [comment]
thanks for your appreciation

**Pull request merged**
